version: "3.8"
 
services:
 
    db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD:  doctheme
        MYSQL_DATABASE: docthemedb
        MYSQL_USER: docthemeuser
        MYSQL_PASSWORD: docthemeuser
      restart: always
      volumes:
        - ./db_data:/var/lib/mysql

    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: doctheme 
        restart: always
        ports:
          - '8081:80'

    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      volumes:
        - ./:/var/www/html
      ports:
       - 80:80
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: docthemedb
        WORDPRESS_DB_PASSWORD: docthemedb
        WORDPRESS_DB_NAME: docthemedb
      restart: always
 
